// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

package messages

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MessageTypes int32

const (
	MessageTypes_HELLO               MessageTypes = 1
	MessageTypes_HELLO_RESP          MessageTypes = 2
	MessageTypes_REGISTER            MessageTypes = 3
	MessageTypes_REGISTER_RESP       MessageTypes = 4
	MessageTypes_LOGIN               MessageTypes = 5
	MessageTypes_LOGIN_RESP          MessageTypes = 6
	MessageTypes_CHANGEPASS          MessageTypes = 7
	MessageTypes_CHANGEPASS_RESP     MessageTypes = 8
	MessageTypes_CHANGEEMAIL         MessageTypes = 9
	MessageTypes_CHANGEEMAIL_RESP    MessageTypes = 10
	MessageTypes_LOGOUT              MessageTypes = 11
	MessageTypes_LOGOUT_RESP         MessageTypes = 12
	MessageTypes_CHANGEDNETWORKVAR   MessageTypes = 13
	MessageTypes_GETCLRESOURCES      MessageTypes = 14
	MessageTypes_GETCLRESOURCESRESP  MessageTypes = 15
	MessageTypes_SERVERCLIENTMESSAGE MessageTypes = 16
	MessageTypes_CLIENTSERVERMESSAGE MessageTypes = 17
	MessageTypes_CLIENTREADY         MessageTypes = 18
	MessageTypes_PLAYERMOVE          MessageTypes = 19
)

var MessageTypes_name = map[int32]string{
	1:  "HELLO",
	2:  "HELLO_RESP",
	3:  "REGISTER",
	4:  "REGISTER_RESP",
	5:  "LOGIN",
	6:  "LOGIN_RESP",
	7:  "CHANGEPASS",
	8:  "CHANGEPASS_RESP",
	9:  "CHANGEEMAIL",
	10: "CHANGEEMAIL_RESP",
	11: "LOGOUT",
	12: "LOGOUT_RESP",
	13: "CHANGEDNETWORKVAR",
	14: "GETCLRESOURCES",
	15: "GETCLRESOURCESRESP",
	16: "SERVERCLIENTMESSAGE",
	17: "CLIENTSERVERMESSAGE",
	18: "CLIENTREADY",
	19: "PLAYERMOVE",
}
var MessageTypes_value = map[string]int32{
	"HELLO":               1,
	"HELLO_RESP":          2,
	"REGISTER":            3,
	"REGISTER_RESP":       4,
	"LOGIN":               5,
	"LOGIN_RESP":          6,
	"CHANGEPASS":          7,
	"CHANGEPASS_RESP":     8,
	"CHANGEEMAIL":         9,
	"CHANGEEMAIL_RESP":    10,
	"LOGOUT":              11,
	"LOGOUT_RESP":         12,
	"CHANGEDNETWORKVAR":   13,
	"GETCLRESOURCES":      14,
	"GETCLRESOURCESRESP":  15,
	"SERVERCLIENTMESSAGE": 16,
	"CLIENTSERVERMESSAGE": 17,
	"CLIENTREADY":         18,
	"PLAYERMOVE":          19,
}

func (x MessageTypes) Enum() *MessageTypes {
	p := new(MessageTypes)
	*p = x
	return p
}
func (x MessageTypes) String() string {
	return proto.EnumName(MessageTypes_name, int32(x))
}
func (x *MessageTypes) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageTypes_value, data, "MessageTypes")
	if err != nil {
		return err
	}
	*x = MessageTypes(value)
	return nil
}

type Hello struct {
	Message          *string `protobuf:"bytes,1,req" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}

func (m *Hello) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type HelloResp struct {
	Message          *string `protobuf:"bytes,1,req" json:"Message,omitempty"`
	PlayerId         *int32  `protobuf:"varint,2,req" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}

func (m *HelloResp) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *HelloResp) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type CommonResponse struct {
	Ok               *bool   `protobuf:"varint,1,req" json:"Ok,omitempty"`
	Err              *string `protobuf:"bytes,2,opt" json:"Err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}

func (m *CommonResponse) GetOk() bool {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return false
}

func (m *CommonResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type Empty struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}

type PlayerMove struct {
	NewX             *float32 `protobuf:"fixed32,1,req,name=newX" json:"newX,omitempty"`
	NewY             *float32 `protobuf:"fixed32,2,req,name=newY" json:"newY,omitempty"`
	NewZ             *float32 `protobuf:"fixed32,3,req,name=newZ" json:"newZ,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerMove) Reset()         { *m = PlayerMove{} }
func (m *PlayerMove) String() string { return proto.CompactTextString(m) }
func (*PlayerMove) ProtoMessage()    {}

func (m *PlayerMove) GetNewX() float32 {
	if m != nil && m.NewX != nil {
		return *m.NewX
	}
	return 0
}

func (m *PlayerMove) GetNewY() float32 {
	if m != nil && m.NewY != nil {
		return *m.NewY
	}
	return 0
}

func (m *PlayerMove) GetNewZ() float32 {
	if m != nil && m.NewZ != nil {
		return *m.NewZ
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.MessageTypes", MessageTypes_name, MessageTypes_value)
}
